### ISSUE TITLE
Convert sleepValue and wakeupValue methods to hookables ones

### ISSUE THREAD

**Issue by romaincazier** [kixe/FieldtypeColor#12]
Hi @kixe,

When trying to use `FieldtypeColor` in a [`FieldtypeMultiplier`](https://processwire.com/store/pro-fields/multiplier/), the values weren’t saved.

After some debugging I noticed the `sleepValue` method wasn’t called at all when saving. Making the method hookable (as it is in the base `Fieldtype` class) fixed the issue. I’d advise also making the `wakeupValue` method hookable.

Thanks!

**Comment by kixe** [comment]
@romaincazier 
Thanks for pointing on this. Fixed.
