### ISSUE TITLE
width property overrided by AdminThemUiKit

### ISSUE THREAD

**Issue by flydev-fr** [kixe/FieldtypeColor#3]
hi @kixe , 

Using the Inputfield with AdminThemuiKit, the inputfield ```width``` is set by uikit to ```auto``` which lead to this result:

![coulor](https://user-images.githubusercontent.com/11658616/37887943-e9977ab6-30c4-11e8-9c37-1c5c5c2c60a9.png)

Adding an explicit size in InputfieldColor.css solve the problem : 

```
input[type=color].FieldtypeColor, input[type=color]#Inputfield_defaultValue  {
	height:2em;
	padding:0;
	width: 80px !important;
}
```

![coulor2](https://user-images.githubusercontent.com/11658616/37887965-0a92d940-30c5-11e8-957f-030acb823f19.png)

**Comment by kixe** [comment]
Thanks. merged.
