### ISSUE TITLE
hsl output

### ISSUE THREAD

**Issue by Jehfen** [kixe/FieldtypeColor#5]
Great module.
I think there might be a bug in the hsl string output.
If the hue value is below 60 (yellow to red), it returns 0.

![image](https://user-images.githubusercontent.com/37275559/64238129-19b7c600-cefe-11e9-8abb-7a93c9d1cc30.png)

results in:
![image](https://user-images.githubusercontent.com/37275559/64238178-3522d100-cefe-11e9-84e8-a3cef9f13c4c.png)

**Comment by Jehfen** [comment]
It's on line 116 of FieldTypeColor.module.
$hue = ($rgb[1] - $rgb[1]) / $d + ($rgb[1] < $rgb[1] ? 6 : 0);
should be
$hue = ($rgb[1] - $rgb[**2**]) / $d + ($rgb[1] < $rgb[1] ? 6 : 0);

**Comment by kixe** [comment]
@junofornow 
Thanks for pointing on this. fixed.
