### ISSUE TITLE
Setting default color when using the inputfield within Combo

### ISSUE THREAD

**Issue by ivangretsky** [kixe/FieldtypeColor#7]
Good day! Thanks for  the module! It is great.

It so happened that I need to use the inputfield for the field in Combo pro field. In this scenario I cannot choose the default color when using the Spectrum plugin. It seems to be set on fieldtype level and cannot be overriden in inputfield.

Is there a way round this? Or could this be easily fixed?

**Comment by kixe** [comment]
> It seems to be set on fieldtype level and cannot be overriden in inputfield.

You can set the property **initValue** to an **InputfieldColor** instance. This will be ignored, if the **value** is other than an empty string. Try out the following code:

```
$inputfield = $modules->get('InputfieldColor');
if (!$inputfield->value) $inputfield->value = ""; // no value set, translate to string
$inputfield->initValue = "#ff0000"; // set default or init value
$inputfield->inputType = 3; // Spectrum Color Picker
```
