### ISSUE TITLE
FieldtypeOptionsColor doesnt display color inside Repeater

### ISSUE THREAD

**Issue by tobisalad** [kixe/FieldtypeColor#9]
When I have a FieldtypeOptionsColor-field inside a Repeater it doesn't display the specified colors as background-color.
Processwire-version: 3.0.200
PHP-version: 8.0

**Comment by kixe** [comment]
Using FieldtypeOptionsColor inside repeater fields with dynamic loading (AJAX) enabled is currently not supported. Go to the **'Details'** tab of the field settings, open the **'Repeater Editor Settings'** and disable **'Dynamic repeater loading'** to make the specified colors visible.

<img width="833" alt="Bildschirmfoto 2022-09-14 um 23 46 23" src="https://user-images.githubusercontent.com/4683120/190269717-323c8e51-c5a1-4771-bfcf-4f29f7e24089.png">

**Comment by tobisalad** [comment]
Thanks!
